app/forms.py
from flask_wtf import FlaskForm
from flask_babel import lazy_gettext as _l
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField(_l('Username'), validators=[DataRequired()])
    password = PasswordField(_l('Password'), validators=[DataRequired()])
    remember_me = BooleanField(_l('Remember Me'))
    submit = SubmitField(_l('Sign In'))

app/__init__.py
from flask import Flask, request, g, redirect, url_for
from flask_babel import Babel
from config import Config

# setup application
app = Flask(__name__)
app.config.from_object(Config)

# import and register blueprints (multiple languages)
from app.blueprints.multilingual import multilingual  # nopep8
app.register_blueprint(multilingual)

# setup babel
babel = Babel(app)


@babel.localeselector
def get_locale():
    if not g.get('lang_code', None):
        g.lang_code = request.accept_languages.best_match(
            app.config['LANGUAGES'])
    return g.lang_code


@app.route('/')
def home():
    g.lang_code = request.accept_languages.best_match(app.config['LANGUAGES'])
    return redirect(url_for('multilingual.index'))

app/blueprints/multilingual/__init__.py
from app.blueprints.multilingual.routes import multilingual

app/blueprints/multilingual/routes.py
from flask import render_template, Blueprint, g, redirect, request, current_app, abort, url_for, flash
from flask_babel import _
from app import app
from app.forms import LoginForm

multilingual = Blueprint('multilingual', __name__, template_folder='templates',
                         url_prefix='/<lang_code>')


@multilingual.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', g.lang_code)


@multilingual.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')


@multilingual.before_request
def before_request():
    if g.lang_code not in current_app.config['LANGUAGES']:
        adapter = app.url_map.bind('')
        try:
            endpoint, args = adapter.match(
                '/en' + request.full_path.rstrip('/?'))
            return redirect(url_for(endpoint, **args), 301)
        except:
            abort(404)

    dfl = request.url_rule.defaults
    if 'lang_code' in dfl:
        if dfl['lang_code'] != request.full_path.split('/')[1]:
            abort(404)


@multilingual.route('/')
def index():
    user = {'username': 'Peter'}
    posts = [
        {
            'author': {'username': 'John'},
            'body': _('Beautiful day in Portland!')
        },
        {
            'author': {'username': 'John'},
            'body': _('Learned something with Python Flask')
        },
        {
            'author': {'username': 'Susan'},
            'body': _('The avengers movie was cool!')
        }
    ]
    return render_template('multilingual/index.html', title=_('Home'), user=user, posts=posts)


@multilingual.route('/cake', defaults={'lang_code': 'en'})
@multilingual.route('/kuchen', defaults={'lang_code': 'de'})
def cake():
    return render_template('multilingual/cake.html', title=_('The Cake is a Lie'))


@multilingual.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        flash('Login requested to user {}, remember_me={}'.format(
            form.username.data, form.remember_me.data))
        return redirect(url_for('multilingual.index'))
    return render_template(
        'multilingual/login.html',
        title=_('Sign In'),
        form=form
    )

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% if title %}
    <title>{{ title }} - Microblog</title>
    {% else %}
    <title>{{_( 'Welcome to Microblog' )}}</title>
    {% endif %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
  </head>
  <body>
    <header id="header">
      <a href="{{ url_for('multilingual.index')}}">{{_('Flask Playground')}}</a>
    </header>
    <nav id="menu">
      <ul>
        <li>
          <a href="{{ url_for('multilingual.index') }}">{{_( 'Home' )}}</a>
        </li>
        <li>
          <a href="{{ url_for('multilingual.cake') }}">{{_( 'Cake' )}}</a>
        </li>
        <li>
          <a href="{{ url_for('multilingual.login') }}">{{_( 'Login' )}}</a>
        </li>
      </ul>
      <div id="languages">
        <ul>
          <li>
            <a href="{{ url_for(request.endpoint, lang_code='en') }}">en</a>
          </li>
          <li>
            <a href="{{ url_for(request.endpoint, lang_code='de') }}">de</a>
          </li>
        </ul>
      </div>
    </nav>
    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %} {% block content %} {% endblock %}
  </body>
</html>